
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MenuIcon } from "lucide-react";
import SidebarMenuItem from "@/components/ui/SidebarMenuItem/SidebarMenuItem";
import Sidebar from "@/components/ui/Sidebar/Sidebar";
import SidebarWrapper from "@/components/ui/Sidebar/SidebarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarWrapper />
        {children}
      </body>
    </html>
  );
}
